"""add auth_core_menu (Phase A shadow menu catalog)

Revision ID: 1edb259a35db
Revises: 7a6391bf99d9
Create Date: 2026-08-07 23:53:40.774462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edb259a35db'
down_revision = '7a6391bf99d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_core_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('menu_name', sa.String(length=128), nullable=False),
    sa.Column('menu_code', sa.String(length=64), nullable=True),
    sa.Column('menu_type', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('component', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('permission', sa.String(length=128), nullable=True),
    sa.Column('module_key', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_core_menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_core_menu')
    # ### end Alembic commands ###
