"""integration: 外部对接中心(企查查数据源+铁建云链导出模板)

Revision ID: 666274823b30
Revises: 1edb259a35db
Create Date: 2026-08-08 00:30:43.735895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666274823b30'
down_revision = '1edb259a35db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scene', sa.String(length=32), nullable=True),
    sa.Column('target_platform', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('file_format', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_template_code'), ['code'], unique=True)

    op.create_table('ext_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('base_url', sa.String(length=256), nullable=True),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('api_secret', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('auth_style', sa.String(length=32), nullable=True),
    sa.Column('cache_days', sa.Integer(), nullable=True),
    sa.Column('timeout_sec', sa.Integer(), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_msg', sa.String(length=512), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ext_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ext_credential_provider'), ['provider'], unique=True)

    op.create_table('ext_endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('param_style', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'code', name='uq_ext_endpoint_provider_code')
    )
    with op.batch_alter_table('ext_endpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ext_endpoint_provider'), ['provider'], unique=False)

    op.create_table('ext_query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint_code', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'endpoint_code', 'cache_key', name='uq_ext_cache_key')
    )
    with op.batch_alter_table('ext_query_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ext_query_cache_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ext_query_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ext_query_cache_provider'), ['provider'], unique=False)

    op.create_table('ext_query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint_code', sa.String(length=64), nullable=True),
    sa.Column('query_key', sa.String(length=128), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ext_query_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ext_query_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ext_query_log_provider'), ['provider'], unique=False)

    op.create_table('export_template_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('target_field', sa.String(length=128), nullable=False),
    sa.Column('source_expr', sa.String(length=128), nullable=True),
    sa.Column('default_value', sa.String(length=256), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['export_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_template_field')
    with op.batch_alter_table('ext_query_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ext_query_log_provider'))
        batch_op.drop_index(batch_op.f('ix_ext_query_log_created_at'))

    op.drop_table('ext_query_log')
    with op.batch_alter_table('ext_query_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ext_query_cache_provider'))
        batch_op.drop_index(batch_op.f('ix_ext_query_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_ext_query_cache_cache_key'))

    op.drop_table('ext_query_cache')
    with op.batch_alter_table('ext_endpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ext_endpoint_provider'))

    op.drop_table('ext_endpoint')
    with op.batch_alter_table('ext_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ext_credential_provider'))

    op.drop_table('ext_credential')
    with op.batch_alter_table('export_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_template_code'))

    op.drop_table('export_template')
    # ### end Alembic commands ###
