"""initial baseline

Revision ID: 8ef3258cfd48
Revises: 
Create Date: 2026-08-05 20:01:32.895272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ef3258cfd48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_migration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('version'))

    op.drop_table('db_migration')
    with op.batch_alter_table('ai_call_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ai_call_log_created'))

    with op.batch_alter_table('approval_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_approval_instance_project_status'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('concrete_ticket', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_contracts_project_supplier'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('location_lng')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('location_lat')
        batch_op.drop_column('location_accuracy')
        batch_op.drop_column('location_time')

    with op.batch_alter_table('equipment_inspection', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('equipment_maintenance', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('equipment_rent_settle', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('material_scrap', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('material_transfer', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_materials_project_cat'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_operation_logs_created'))

    with op.batch_alter_table('payment_applications', schema=None) as batch_op:
        batch_op.drop_column('dept_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('purchase_requisition', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_reconciliations_project_contract'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('stock_check', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('stock_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_stock_ins_project_date'))
        batch_op.drop_index(batch_op.f('idx_stock_ins_project_status'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('stock_outs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_stock_outs_project_date'))
        batch_op.drop_index(batch_op.f('idx_stock_outs_project_status'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('turnover_material', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('turnover_record', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnover_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('turnover_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('stock_outs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('idx_stock_outs_project_status'), ['project_id', 'approval_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_stock_outs_project_date'), ['project_id', 'stock_out_date'], unique=False)

    with op.batch_alter_table('stock_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('idx_stock_ins_project_status'), ['project_id', 'approval_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_stock_ins_project_date'), ['project_id', 'stock_in_date'], unique=False)

    with op.batch_alter_table('stock_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('idx_reconciliations_project_contract'), ['project_id', 'contract_id'], unique=False)

    with op.batch_alter_table('purchase_requisition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('payment_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_operation_logs_created'), ['created_at'], unique=False)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('idx_materials_project_cat'), ['project_id', 'category_id'], unique=False)

    with op.batch_alter_table('material_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('material_scrap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('equipment_rent_settle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('equipment_maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('equipment_inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('location_accuracy', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('location_lat', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_lng', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('idx_contracts_project_supplier'), ['project_id', 'supplier_id'], unique=False)

    with op.batch_alter_table('concrete_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('approval_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('idx_approval_instance_project_status'), ['project_id', 'status'], unique=False)

    with op.batch_alter_table('ai_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ai_call_log_created'), ['created_at'], unique=False)

    op.create_table('db_migration',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('applied_at', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), server_default=sa.text("'success'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('db_migration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('version'), ['version'], unique=True)

    # ### end Alembic commands ###
